routes/web.php
<?php

Route::name('tes')->get('tes', function () {
    return view('tes');
});
Route::group(['namespace' => 'Blog'], function() {
    Route::name('home')->get('/', 'HomeController@index');

    Route::name('artikel.list')->get('/artikel', 'NewsController@index');
    Route::name('artikel.detail')->get('/artikel/{slug}', 'NewsController@show');

    // Route::name('tentang_kami')->get('tentang-kami', function () {
    //     return view('front.about_us');
    // });
    Route::name('kontak_kami')->get('kontak-kami', 'ContactController@index');
    Route::name('kategori.list')->get('/kategori/{slug}', 'HomeController@category_detail');
    Route::name('agenda.index')->get('/agenda', 'ScheduleController@index');
    Route::name('agenda.list')->get('/agenda/{detail}', 'ScheduleController@detail');

    Route::name('pages.detail')->get('/pages/{slug}', 'HomeController@pages');
    Route::name('tag.list')->get('/tag/{slug}', 'HomeController@tag');
    Route::name('comment.post')->post('/comment', 'HomeController@comment');
    Route::name('searchajax')->get('/searchajax', 'HomeController@autoComplete');
    Route::name('portfolio')->get('/portfolio', 'HomeController@gallery');
    // Route::name('search')->post('/search', 'SearchController');
    Route::name('home.contact')->post('/home/contact', 'ContactController@sendMail');
});

Route::group(['prefix' => 'adm'], function () {
  Auth::routes();

  Route::group(['namespace' => 'Admin'], function() {

    Route::name('adm')->get('/', 'HomeController@index');

    Route::resource('/agenda', 'AgendaController');
    Route::get('/agenda/edit/{id}', 'AgendaController@edit');
    Route::put('/agenda/update/{id}', 'AgendaController@update');
    Route::get('/agenda/show/{id}', 'AgendaController@show');

    Route::resource('/album', 'AlbumController', ['names' => 'adm.album']);
    Route::resource('/banner', 'BannerController', ['names' => 'adm.banner']);
    Route::resource('/category', 'CategoryController', ['names' => 'adm.category']);
    Route::resource('/client', 'ClientController', ['names' => 'adm.client']);
    Route::resource('/comment', 'CommentController', ['names' => 'adm.comment']);
    // Route::name('adm.comment.index')->get('/comment', 'CommentController@index');
    // Route::name('adm.comment.show')->get('/comment/show/{comment}', 'CommentController@show');
    Route::name('comment.destroy')->delete('/comment/destroy/{comment}', 'CommentController@destroy');

    Route::name('contact.count')->get('/contact/count-message', 'ContactController@countMessage');
    Route::resource('/contact', 'ContactController', ['names' => 'adm.contact']);

    Route::resource('/galery', 'GaleryController', ['names' => 'adm.galery']);
    Route::resource('/identity', 'IdentityController', ['names' => 'adm.identity']);
    Route::resource('/identity_social', 'IdentitySocialController', ['names' => 'adm.identity_social']);
    Route::resource('/menu', 'MenuController', ['names' => 'adm.menu']);
    Route::resource('/news', 'NewsController', ['names' => 'adm.news']);
    Route::resource('/staticpages', 'StaticpagesController', ['names' => 'adm.staticpages']);
    Route::resource('/tag', 'TagController', ['names' => 'adm.tag']);
    Route::resource('/user', 'UserController', ['names' => 'adm.user']);

    Route::name('profil.change_password')->get('/profil/change-password/{id}', 'UserPasswordController@changePassword');
    Route::name('profil.change_password.update')->put('/profil/change-password/{id}', 'UserPasswordController@update');
    Route::name('profil.store')->post('/profil/store', 'UserProfilController@store');
    Route::name('profil.update')->put('/profil/update/{id}', 'UserProfilController@update');

    Route::get('/user/getposts', ['as'=>'adm.user.getposts','uses'=>'UserController@getPosts']);
    Route::name('adm.profil')->get('/profil', 'UserController@profil');
    Route::name('adm.profil.edit')->get('/edit_profil/{id}', 'UserController@edit_profil');

  });

});

app/Http/Controllers/Admin/ClientController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use DB;
use App\Http\Requests\ClientRequest;
use Illuminate\Support\Str;
use Storage;


use App\ClientModel;
use Ramsey\Uuid\Uuid;
use Session;
use Alert;
use Intervention\Image\Facades\Image;

class ClientController extends Controller
{
    public function index()
    {
        $clients = ClientModel::select('id', 'url', 'name', 'picture', 'created_at')
                  ->orderBy('created_at', 'desc')
                  ->get();
        return view('admin.client.index', compact('clients'));
    }


    public function create()
    {
        return view('admin.client.create');
    }

    public function store(ClientRequest $request)
    {
        request()->validate([
            'picture' => 'required|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);
        $photoName = time().'.'.$request->picture->getClientOriginalExtension();
        $request->picture->move(public_path('storage/uploads/client'), $photoName);
        $data['picture']= $photoName;

        $data['url']        = $request->url;
        $data['name']       = $request->name;
        $data['created_at'] = date('Y-m-d H:i:s');

        if (ClientModel::insert($data)) {
            Alert::success('Data berhasil ditambah !', 'Sukses');
            return redirect('adm/client');
         }else{
            Alert::error('Silahkan di coba lagi !', 'Error');
            return redirect('adm/client');
         }
    }

    public function edit($id)
    {
        if ($id!='') {
            $data['client'] = ClientModel::where('id', $id)->first();
            return view('admin.client.edit', $data);
        }
    }

    public function update(ClientRequest $request, $id)
    {
        if ($request->picture != '') {
            request()->validate([
                'picture' => 'required|mimes:jpeg,png,jpg|max:2048',
            ]);
            \File::delete('storage/uploads/client/'.$request->picture_old);
            $photoName = time().'.'.$request->picture->getClientOriginalExtension();
            $request->picture->move(public_path('storage/uploads/client'), $photoName);
            $data['picture'] = $photoName;
        }else{
            $data['picture']    = $request->picture_old;
        }

        $data['url']        = $request->url;
        $data['name']       = $request->name;
        $data['updated_at'] = date('Y-m-d H:i:s');

        if (ClientModel::where('id', $id)->update($data)) {
            Alert::success('Data berhasil disimpan', 'Sukses');
            return redirect('adm/client');
         }else{
            Alert::error('Silahkan di coba lagi !', 'Error');
            return redirect('adm/client/edit/'.$id);
         }
    }

    public function destroy($id)
    {
        if ($id != '') {
            $client = ClientModel::where('id', $id)->first();
              \File::delete('storage/uploads/client/'.$client->picture);
            if (ClientModel::where('id', $id)->delete()){
                Alert::success('Data berhasil dihapus', 'Sukses');
                return redirect('adm/client');
            }else{
                Alert::error('Silahkan di coba lagi !', 'Error');
                return redirect('adm/client');
            }
        }
    }
}

resources/views/admin/client/create.blade.php
@extends('layouts.admin.template')
@section('title', 'Add Client')
@section('breadcrumb')
<div id="breadcrumb">
	<ul class="breadcrumb">
		 <li><i class="fa fa-home"></i><a onclick="location.href='{{ route('adm') }}'"> Home</a></li>
		 <li><a onclick="location.href='{{ route('adm.client.index') }}'">Client</a></li>
		 <li class="active">Add</li>
	</ul>
</div><!-- /breadcrumb-->
@endsection
@section('content')
<div class="panel panel-primary">
	<div class="panel-heading">Add Client</div>
	<div class="panel-body">
		{!! Form::open(['route' => 'adm.client.store', 'methode' => 'POST', 'class' => 'form-horizontal', 'enctype' => 'multipart/form-data']) !!}

			<div class="form-group">
				<label for="name" class="col-sm-2 control-label">Client Name</label>
				<div class="col-sm-10">
					<input type="text" name="name" class="form-control" id="name" placeholder="Client Name" value="{{ old('name') }}">
				</div>
			</div>
			<div class="form-group">
				<label for="url" class="col-sm-2 control-label">Client URL</label>
				<div class="col-sm-10">
					<input type="text" name="url" class="form-control" id="url" placeholder="Client URL" value="{{  old('url') }}">
				</div>
			</div>
			<div class="form-group">
				<label for="picture" class="col-sm-2 control-label">Picture</label>
				<div class="col-sm-5">
					<div class="upload-file">
						<input type="file" name="picture" id="picture" class="picture">
						<label data-title="Select file" for="picture">
							<span data-title="No file selected..."></span>
						</label>
					</div>
					<br>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Simpan</button>
					<a onclick="location.href='{{ route('adm.client.index') }}'" class="btn btn-danger"><i class="fa fa-arrow-left"></i> Kembali</a>
				</div>
			</div>

		{!! Form::close() !!}
	</div>
</div>
@endsection

@section('style')
<link href="{{ asset('admin/css/gritter/jquery.gritter.css') }}" rel="stylesheet">
@endsection

@section('js')
<script src="{{ asset('admin/js/jquery.gritter.min.js') }}"></script>
<script>
	$('.picture').change(function()	{
		var filename = $(this).val().split('\\').pop();
		$(this).parent().find('span').attr('data-title',filename);
		$(this).parent().find('label').attr('data-title','Change file');
		$(this).parent().find('label').addClass('selected');
	});
</script>

@if(count($errors) > 0)
    @foreach($errors->all() as $error)
        <script>
			$.gritter.add({
				title: '<i class="fa fa-warning"></i> Error',
				text: '{{ $error }}',
				sticky: false,
				time: '5000',
				class_name: 'gritter-danger'
			});
        </script>
    @endforeach
@endif

@endsection

resources/views/admin/client/edit.blade.php
@extends('layouts.admin.template')
@section('title', 'Edit Client')
@section('breadcrumb')
<div id="breadcrumb">
	<ul class="breadcrumb">
		 <li><i class="fa fa-home"></i><a href="" onclick="location.href='{{ route('adm') }}'"> Home</a></li>
		 <li><a href="" onclick="location.href='{{ route('adm.client.index') }}'">Client</a></li>
		 <li class="active">Edit</li>
	</ul>
</div><!-- /breadcrumb-->
@endsection
@section('content')
<div class="panel panel-primary">
	<div class="panel-heading">Edit Client</div>
	<div class="panel-body">
		{!! Form::open(['route' => ['adm.client.update', $client->id], 'method' => 'PUT', 'class' => 'form-horizontal', 'enctype' => 'multipart/form-data']) !!}

			<div class="form-group">
				<label for="name" class="col-sm-2 control-label">Client Name</label>
				<div class="col-sm-10">
					<input type="text" name="name" class="form-control" id="name" placeholder="Client Name" value="{{ $client->name }}" autocomplete="off">
				</div>
			</div>
			<div class="form-group">
				<label for="url" class="col-sm-2 control-label">Client URL</label>
				<div class="col-sm-10">
					<input type="text" name="url" class="form-control" id="url" placeholder="Client URL" value="{{ $client->url }}" autocomplete="off">
				</div>
			</div>
			<div class="form-group">
				<label for="picture" class="col-sm-2 control-label">Picture</label>
				<div class="col-sm-5">
					<div class="upload-file">
						<input type="file" name="picture" id="picture" class="picture">
						<label data-title="Select file" for="picture">
							<span data-title="No file selected..."></span>
						</label>
					</div>
					<br>
					<br>
					<input type="hidden" name="picture_old" value="{{ $client->picture }}">
					<span class="help-block alert alert-info"><img width="100%" class="thumbnail" src="{{ url('/storage/uploads/client/'. $client->picture) }}"></span>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Simpan</button>
					<a onclick="location.href='{{ route('adm.client.index') }}'" class="btn btn-danger"><i class="fa fa-arrow-left"></i> Kembali</a>
				</div>
			</div>

		{!! Form::close() !!}
	</div>
</div>
@endsection

@section('style')
<link href="{{ asset('admin/css/gritter/jquery.gritter.css') }}" rel="stylesheet">
@endsection

@section('js')
<script src="{{ asset('admin/js/jquery.gritter.min.js') }}"></script>
<script>
	$('.picture').change(function()	{
		var filename = $(this).val().split('\\').pop();
		$(this).parent().find('span').attr('data-title',filename);
		$(this).parent().find('label').attr('data-title','Change file');
		$(this).parent().find('label').addClass('selected');
	});
</script>

@if(count($errors) > 0)
    @foreach($errors->all() as $error)
        <script>
			$.gritter.add({
				title: '<i class="fa fa-warning"></i> Error',
				text: '{{ $error }}',
				sticky: false,
				time: '5000',
				class_name: 'gritter-danger'
			});
        </script>
    @endforeach
@endif

@endsection

resources/views/admin/client/index.blade.php
@extends('layouts.admin.template')
@section('title', 'Client')
@section('breadcrumb')
<div id="breadcrumb">
	<ul class="breadcrumb">
		 <li><i class="fa fa-home"></i><a onclick="location.href='{{ route('adm') }}'"> Home</a></li>
		 <li class="active">Client</li>
	</ul>
</div>
@endsection
@section('content')
<div class="panel panel-primary table-responsive">
	<div class="panel-heading">
		&nbsp;
	</div>
	<div class="padding-md clearfix">
		@section('button')
		<a onclick="location.href='{{ route('adm.client.create') }}'" class="btn btn-primary btn-small"><i class="fa fa-plus"></i> Add Client</a>
		@endsection
		<table class="table table-condensed table-bordered" id="dataTable">
			<thead>
				<tr>
					<th width="20px">No</th>
					<th>URL</th>
					<th>Name</th>
					<th>Logo</th>
					<th>Created At</th>
					<th width="100px">Action</th>
				</tr>
			</thead>
			<tbody>
				@php $no=0; @endphp
				@forelse($clients as $r)
				@php $no++; @endphp
				<tr>
					<td>{{ $no }}</td>
					<td>{{ $r->name }}</td>
					<td>{{ $r->url }}</td>
					<td>{{ $r->picture }}</td>
					<td>{{ $r->created_at }}</td>
					<td>
						@if(!empty($r->picture))
						<a class="gallery-zoom btn btn-xs btn-info" href="{{ url('storage/uploads/client/'.$r->picture) }}"><i class="fa fa-eye"></i></a>
						@endif
						<a href="{{ route('adm.client.edit', $r->id) }}" class="btn btn-xs btn-primary"><i class="fa fa-pencil"></i></a>
						{{ Form::open(['route' => ['adm.client.destroy', $r->id], 'method' => 'DELETE', 'class' => 'delete_form', 'style' => 'display:inline']) }}
						<button class="btn btn-danger btn-xs delete_button"><i class="fa fa-trash"></i></button>
						{{ Form::close() }}
					</td>
				</tr>
				@empty
				<tr>
					<td colspan="6">Belum ada data !</td>
				</tr>
				@endforelse
			</tbody>
		</table>
	</div>
</div>
@endsection

@section('style')
<link href="{{ asset('admin/css/jquery.dataTables_themeroller.css') }}" rel="stylesheet">
<link href="{{ asset('admin/css/sweetalert.css') }}" rel="stylesheet">
<link href="{{ asset('admin/css/colorbox/colorbox.css') }}" rel="stylesheet">
@endsection

@section('js')
<script src="{{ asset('admin/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin/js/sweetalert.min.js') }}"></script>
<script src="{{ asset('admin/js/jquery.colorbox.min.js') }}"></script>

<script>
		$('#dataTable').dataTable( {
			"bJQueryUI": true,
			"bLengthChange": false,
			"sPaginationType": "full_numbers"
		});
		$('.gallery-zoom').colorbox({
			rel:'gallery',
			maxWidth:'90%',
			width:'800px'
		});
    $('button.delete_button').on('click', function(e){
    	e.preventDefault();
    	var self = $(this);
    	swal({
        title: "Alert",
        text: "Apakah anda yakin ingin menghapus data ini ?",
        type: "warning",
        showCancelButton: true,
        confirmButtonColor: "#cc3f44",
        confirmButtonText: "Hapus",
        cancelButtonText : "Batal",
        closeOnConfirm: false,
        closeOnCancel: false
    	},
    	function(isConfirm) {
	        if(isConfirm){
	        	self.parents(".delete_form").submit();
	        }else{
	        	swal('Cancelled', 'Data anda gagal dihapus !', 'error');
	        }
	    });
    });
</script>
@endsection