routes/web.php
<?php

Route::name('tes')->get('tes', function () {
    return view('tes');
});
Route::group(['namespace' => 'Blog'], function() {
    Route::name('home')->get('/', 'HomeController@index');

    Route::name('artikel.list')->get('/artikel', 'NewsController@index');
    Route::name('artikel.detail')->get('/artikel/{slug}', 'NewsController@show');

    // Route::name('tentang_kami')->get('tentang-kami', function () {
    //     return view('front.about_us');
    // });
    Route::name('kontak_kami')->get('kontak-kami', 'ContactController@index');
    Route::name('kategori.list')->get('/kategori/{slug}', 'HomeController@category_detail');
    Route::name('agenda.index')->get('/agenda', 'ScheduleController@index');
    Route::name('agenda.list')->get('/agenda/{detail}', 'ScheduleController@detail');

    Route::name('pages.detail')->get('/pages/{slug}', 'HomeController@pages');
    Route::name('tag.list')->get('/tag/{slug}', 'HomeController@tag');
    Route::name('comment.post')->post('/comment', 'HomeController@comment');
    Route::name('searchajax')->get('/searchajax', 'HomeController@autoComplete');
    Route::name('portfolio')->get('/portfolio', 'HomeController@gallery');
    // Route::name('search')->post('/search', 'SearchController');
    Route::name('home.contact')->post('/home/contact', 'ContactController@sendMail');
});

Route::group(['prefix' => 'adm'], function () {
  Auth::routes();

  Route::group(['namespace' => 'Admin'], function() {

    Route::name('adm')->get('/', 'HomeController@index');

    Route::resource('/agenda', 'AgendaController');
    Route::get('/agenda/edit/{id}', 'AgendaController@edit');
    Route::put('/agenda/update/{id}', 'AgendaController@update');
    Route::get('/agenda/show/{id}', 'AgendaController@show');

    Route::resource('/album', 'AlbumController', ['names' => 'adm.album']);
    Route::resource('/banner', 'BannerController', ['names' => 'adm.banner']);
    Route::resource('/category', 'CategoryController', ['names' => 'adm.category']);
    Route::resource('/client', 'ClientController', ['names' => 'adm.client']);
    Route::resource('/comment', 'CommentController', ['names' => 'adm.comment']);
    // Route::name('adm.comment.index')->get('/comment', 'CommentController@index');
    // Route::name('adm.comment.show')->get('/comment/show/{comment}', 'CommentController@show');
    Route::name('comment.destroy')->delete('/comment/destroy/{comment}', 'CommentController@destroy');

    Route::name('contact.count')->get('/contact/count-message', 'ContactController@countMessage');
    Route::resource('/contact', 'ContactController', ['names' => 'adm.contact']);

    Route::resource('/galery', 'GaleryController', ['names' => 'adm.galery']);
    Route::resource('/identity', 'IdentityController', ['names' => 'adm.identity']);
    Route::resource('/identity_social', 'IdentitySocialController', ['names' => 'adm.identity_social']);
    Route::resource('/menu', 'MenuController', ['names' => 'adm.menu']);
    Route::resource('/news', 'NewsController', ['names' => 'adm.news']);
    Route::resource('/staticpages', 'StaticpagesController', ['names' => 'adm.staticpages']);
    Route::resource('/tag', 'TagController', ['names' => 'adm.tag']);
    Route::resource('/user', 'UserController', ['names' => 'adm.user']);

    Route::name('profil.change_password')->get('/profil/change-password/{id}', 'UserPasswordController@changePassword');
    Route::name('profil.change_password.update')->put('/profil/change-password/{id}', 'UserPasswordController@update');
    Route::name('profil.store')->post('/profil/store', 'UserProfilController@store');
    Route::name('profil.update')->put('/profil/update/{id}', 'UserProfilController@update');

    Route::get('/user/getposts', ['as'=>'adm.user.getposts','uses'=>'UserController@getPosts']);
    Route::name('adm.profil')->get('/profil', 'UserController@profil');
    Route::name('adm.profil.edit')->get('/edit_profil/{id}', 'UserController@edit_profil');

  });

});

app/Http/Controllers/Admin/StaticpagesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\StaticpagesRequest;
use Illuminate\Support\Str;

use App\StaticpagesModel;
use Ramsey\Uuid\Uuid;
use Session;
use Alert;

class StaticpagesController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $static = StaticpagesModel::select('id','title', 'slug', 'active', 'created_at')
            ->orderBy('staticpages.created_at', 'desc')->get();
        return view('admin.staticpages.index', compact('static'));
    }

    public function create()
    {
        return view('admin.staticpages.create');
    }

    public function store(StaticpagesRequest $request)
    {
      if ($request->hasFile('picture')) {

        $photoName = time().'.'.$request->picture->getClientOriginalExtension();
        $request->picture->move(public_path('storage/uploads/static_pages'), $photoName);
        $data['id']         = Uuid::uuid4()->toString();
        $data['title']      = $request->title;
        $data['slug']       = Str::slug($request->title);
        $data['content']    = $request->content;
        $data['picture']    = $photoName;
        $data['active']     = $request->active;
        $data['created_at'] = date('Y-m-d H:i:s');

      }else{

        $data['id']         = Uuid::uuid4()->toString();
        $data['title']      = $request->title;
        $data['slug']       = Str::slug($request->title);
        $data['content']    = $request->content;
        $data['active']     = $request->active;
        $data['created_at'] = date('Y-m-d H:i:s');

      }

        if (StaticpagesModel::insert($data)) {
            Alert::success('Data berhasil disimpan', 'Sukses');
            return redirect('adm/staticpages');
         }else{
            Alert::error('Silahkan di coba lagi !', 'Error');
            return redirect('adm/staticpages');
         }
    }

    public function show($id)
    {
      if ($id!='') {
        $data['static'] = StaticpagesModel::select('title', 'slug', 'content', 'picture', 'active', 'created_at')
                        ->where('id', $id)
                        ->first();
          return view('admin.staticpages.show', $data);
      }
    }

    public function edit($id)
    {
        if ($id!='') {
            $data['static'] = StaticpagesModel::where(array('id' => $id))->get()->first();
            return view('admin.staticpages.edit', $data);
        }
    }

    public function update(StaticpagesRequest $request, $id)
    {

        if (isset($request->picture)) {

          $photoName = time().'.'.$request->picture->getClientOriginalExtension();
          $request->picture->move(public_path('storage/uploads/static_pages'), $photoName);

          $data['title']        = $request->title;
          $data['slug']         = Str::slug($request->title);
          $data['content']      = $request->content;
          $data['active']       = $request->active;
          $data['picture']      = $photoName;
          $data['updated_at']   = date('Y-m-d H:i:s');

        }else{
          $data['title']        = $request->title;
          $data['slug']         = Str::slug($request->title);
          $data['content']      = $request->content;
          $data['active']       = $request->active;
          $data['updated_at']   = date('Y-m-d H:i:s');
        }

        if (StaticpagesModel::where('id', $id)->update($data)) {
            Alert::success('Data berhasil disimpan', 'Sukses');
            return redirect('adm/staticpages');
         }else{
            Alert::error('Silahkan di coba lagi !', 'Error');
            return redirect('adm/staticpages/edit/'.$id);
         }
    }

    public function destroy($id)
    {
        if ($id != '') {
            if (StaticpagesModel::where('id', $id)->delete()){
                   Alert::success('Data berhasil dihapus', 'Sukses');
                    return redirect('adm/staticpages');
            }else{
                Alert::error('Silahkan di coba lagi !', 'Error');
                return redirect('adm/staticpages');
            }
        }
    }
}

resources/views/admin/staticpages/create.blade.php
@extends('layouts.admin.template')
@section('title', 'Tambah Halaman Statis')

@section('breadcrumb')
<div id="breadcrumb">
	<ul class="breadcrumb">
		 <li><i class="fa fa-home"></i><a onclick="location.href='{{ route('adm') }}'"> Home</a></li>
		 <li></i><a onclick="location.href='{{ route('adm.staticpages.index') }}'"> Halaman Statis</a></li>
		 <li class="active">Tambah</li>
	</ul>
</div>
@endsection

@section('content')
<div class="panel panel-primary">
	<div class="panel-heading">@yield('title')</div>
	<div class="panel-body">
		{!! Form::open(array('route' => 'adm.staticpages.store', 'methode' => 'POST', 'class' => 'form-horizontal', 'enctype' => 'multipart/form-data')) !!}

		<div class="form-group">
			<label for="title" class="col-sm-2 control-label">Judul</label>
			<div class="col-sm-10">
				<input type="text" name="title" class="form-control" id="title" placeholder="Judul" value="">
			</div>
		</div>

		<div class="form-group">
			<label for="content" class="col-sm-2 control-label">Konten</label>
			<div class="col-sm-10">
				<textarea id="editor" name="content" placeholder="Masukkan konten halamn statis anda disini..." class="form-control" rows="6"></textarea>
			</div>
		</div>
		<div class="form-group">
			<label for="picture" class="col-sm-2 control-label">Gambar</label>
			<div class="col-sm-5">
				<div class="upload-file">
					<input type="file" name="picture" id="picture" class="picture">
					<label data-title="Select file" for="picture">
						<span data-title="No file selected..."></span>
					</label>
				</div>
				<br>
			</div>
		</div>
		<div class="form-group">
			<label for="active" class="col-sm-2 control-label">Status</label>
			<div class="col-lg-10">
				<label class="label-radio inline">
					<input type="radio" name="active" value="Y">
					<span class="custom-radio"></span>
					Active
				</label>
				<label class="label-radio inline">
					<input type="radio" name="active" value="N">
					<span class="custom-radio"></span>
					Non Active
				</label>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Simpan</button>
				<a onclick="location.href='{{ route('adm.staticpages.index') }}'" class="btn btn-danger"><i class="fa fa-arrow-left"></i> Kembali</a>
			</div>
		</div>
		{!! Form::close() !!}
	</div>
</div>
@endsection

@section('style')
<link href="{{ asset('ckeditor/content.css') }}" rel="stylesheet"/>
<link href="{{ asset('admin/css/gritter/jquery.gritter.css') }}" rel="stylesheet">
@endsection

@section('js')
<script src="{{ asset('ckeditor/ckeditor/ckeditor.js') }}"></script>
<script src="{{ asset('admin/js/jquery.gritter.min.js') }}"></script>
<script>
	CKEDITOR.replace( 'editor');

	$('.picture').change(function()	{
		var filename = $(this).val().split('\\').pop();
		$(this).parent().find('span').attr('data-title',filename);
		$(this).parent().find('label').attr('data-title','Change file');
		$(this).parent().find('label').addClass('selected');
	});
</script>

@if(count($errors) > 0)
    @foreach($errors->all() as $error)
        <script>
			$.gritter.add({
				title: '<i class="fa fa-warning"></i> Error',
				text: '{{ $error }}',
				sticky: false,
				time: '5000',
				class_name: 'gritter-danger'
			});
        </script>
    @endforeach
@endif

@endsection

resources/views/admin/staticpages/edit.blade.php
@extends('layouts.admin.template')
@section('title', 'Edit Halaman Statis')
@section('content')

<section class="panel panel-primary">
	<header class="panel-heading">Edit Halaman Status</header>
	<div class="panel-body">

	{!! Form::open(['route' => ['adm.staticpages.update', $static->id], 'method' => 'PUT', 'class' => 'form-horizontal']) !!}

		<div class="form-group">
			<label for="title" class="col-sm-2 control-label">Judul</label>
			<div class="col-sm-10">
				<input type="text" name="title" class="form-control" id="title" placeholder="Judul" value="{{ $static->title }}">
			</div>
		</div>

		<div class="form-group">
			<label for="content" class="col-sm-2 control-label">Konten</label>
			<div class="col-sm-10">
				<textarea id="content" name="content" placeholder="Masukan konten halaman statis anda disini..." class="form-control" rows="6">
					{{ $static->content }}
				</textarea>
			</div>
		</div>
		<div class="form-group">
			<label for="picture" class="col-sm-2 control-label">Gambar</label>
			<div class="col-sm-5">
				<div class="upload-file">
					<input type="file" name="picture" id="picture" class="picture">
					<label data-title="Select file" for="picture">
						<span data-title="No file selected..."></span>
					</label>
				</div>
				<br>
			</div>
		</div>
		<div class="form-group">
			<label for="active" class="col-sm-2 control-label">Status</label>
			<div class="col-lg-10">
				@if ($static->active == 'Y')
					<label class="label-radio inline">
						<input type="radio" name="active" value="Y" checked>
						<span class="custom-radio"></span>
						Aktif
					</label>
					<label class="label-radio inline">
						<input type="radio" name="active" value="N">
						<span class="custom-radio"></span>
						Non Aktif
					</label>
		        @else
					<label class="label-radio inline">
						<input type="radio" name="active" value="Y">
						<span class="custom-radio"></span>
						Aktif
					</label>
					<label class="label-radio inline">
						<input type="radio" name="active" value="N" checked>
						<span class="custom-radio"></span>
						Non Aktif
					</label>
		        @endif

			</div><!-- /.col -->
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Simpan</button>
				<a onclick="location.href='{{ route('adm.staticpages.index') }}'" class="btn btn-danger"><i class="fa fa-arrow-left"></i> Kembali</a>
			</div>
		</div>
		{!! Form::close() !!}
	</div>
</section>
@endsection


@section('style')
<link href="{{ asset('ckeditor/content.css') }}" rel="stylesheet"/>
<link href="{{ asset('admin/css/gritter/jquery.gritter.css') }}" rel="stylesheet">
@endsection

@section('js')
<script src="{{ asset('ckeditor/ckeditor/ckeditor.js') }}"></script>
<script src="{{ asset('admin/js/jquery.gritter.min.js') }}"></script>
<script>
CKEDITOR.replace( 'content' );
</script>
@if(count($errors) > 0)
    @foreach($errors->all() as $error)
        <script>
			$.gritter.add({
				title: '<i class="fa fa-warning"></i> Error',
				text: '{{ $error }}',
				sticky: false,
				time: '5000',
				class_name: 'gritter-danger'
			});
        </script>
    @endforeach
@endif
@endsection

resources/views/admin/staticpages/index.blade.php
@extends('layouts.admin.template')
@section('title', 'Halaman Statis')
@section('breadcrumb')
<div id="breadcrumb">
	<ul class="breadcrumb">
		 <li><i class="fa fa-home"></i><a onclick="location.href='{{ route('adm') }}'"> Home</a></li>
		 <li class="active">@yield('title')</li>
	</ul>
</div>
@endsection
@section('content')
<div class="panel panel-primary table-responsive">
	<div class="panel-heading">&nbsp;</div>
	<div class="padding-md clearfix">
		@section('button')
		<a onclick="location.href='{{ route('adm.staticpages.create') }}'" class="btn btn-primary btn-small"><i class="fa fa-plus"></i> Add @yield('title') </a>
		@endsection
		<table class="table table-condensed table-bordered" id="dataTable">
			<thead>
				<tr>
					<th width="20px">No</th>
					<th>Judul</th>
					<th>Tanggal Post</th>
					<th>Aktif</th>
					<th width="100px">Aksi</th>
				</tr>
			</thead>
			<tbody>
				@if(!$static->isEmpty())
				@php $no=0; @endphp
				@foreach($static as $r)
				@php $no++; @endphp
				<tr>
					<td>{{ $no }}</td>
					<td>{{ $r->title }}</td>
					<td>{{ tglIndo($r->created_at) }}</td>
					<td>{!! $r->active == 'Y' ? '<i class=\'fa fa-check\'></i>' : '<i class=\'fa fa-times\'></i>' !!}</td>
					<td>
						<button type="button" class="btn btn-info btn-xs btn-detail" data-toggle="modal" data-target=".bs-example-modal-md" id="{{ url('adm/staticpages/show/'.$r->id) }}"><i class="fa fa-eye"></i></button>
						<a href="{{ route('adm.staticpages.edit', $r->id) }}" class="btn btn-xs btn-primary"><i class="fa fa-pencil"></i></a>
						{!! Form::open(['route' => ['adm.staticpages.destroy', $r->id], 'method' => 'DELETE', 'class' => 'delete_form', 'style' => 'display:inline']) !!}
						<button class="btn btn-danger btn-xs delete_button"><i class="fa fa-trash"></i></button>
						{!! Form::close() !!}
					</td>
				</tr>
				@endforeach
				@endif
			</tbody>
		</table>
	</div><!-- /.padding-md -->
</div>
<div class="modal fade bs-example-modal-md" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-body">
        <div id="modalcontent"></div>
      </div>
    </div>
  </div>
</div>
@endsection

@section('style')
<link href="{{ asset('admin/css/jquery.dataTables_themeroller.css') }}" rel="stylesheet">
<link href="{{ asset('admin/css/sweetalert.css') }}" rel="stylesheet">
@endsection

@section('js')
<script src="{{ asset('admin/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin/js/clipboard.js') }}"></script>
<script src="{{ asset('admin/js/sweetalert.min.js') }}"></script>
<script>
	$(function	()	{
		$('.btn-detail').on('click', function(){
				var id = $(this).attr('id');
				$('#modalcontent').load(id);
		});
		var clipboard = new Clipboard('.copy-button');
		$('#dataTable').dataTable( {
			"bJQueryUI": true,
			"bLengthChange": false,
			"sPaginationType": "full_numbers"
		});
		$('button.delete_button').on('click', function(e){
			e.preventDefault();
			var self = $(this);
			swal({
				title: "Alert",
				text: "Apakah anda yakin ingin menghapus data ini ?",
				type: "warning",
				showCancelButton: true,
				confirmButtonColor: "#cc3f44",
				confirmButtonText: "Hapus",
				cancelButtonText : "Batal",
				closeOnConfirm: false,
				closeOnCancel: false
			},
			function(isConfirm) {
					if(isConfirm){
						self.parents(".delete_form").submit();
					}else{
						swal('Cancelled', 'Data anda gagal dihapus !', 'error');
					}
			});
		});
	});
</script>
@endsection

resources/views/admin/staticpages/show.blade.php
<div class="panel blog-container">
	<div class="panel-body">
		<h4>{{ $static->title }}</h4>
		<small class="text-muted">Oleh <a href="#"></a> | Tanggal {{ tglIndo($static->created_at) }} </small>
		<div class="seperator"></div>
    <div class="input-group">
				<input id="slug" type="text" value="{{ 'pages/'.$static->slug }}" class="form-control">
				<span class="input-group-btn">
					<button class="btn btn-success copy-button" data-clipboard-action="copy" data-clipboard-target="#slug">Copy</button>
				</span>
			</div>
		<div class="seperator"></div>
		@if( $static->picture != '' )
		<img width="200px" class="img-thumbnail" style="float:left; margin-right:10px" src="{{ url('storage/uploads/static_pages/'.$static->picture) }}" alt="{{ $static->title }}">
		@endif
		{!! $static->content !!}

	</div>
</div>