routes/web.php
<?php

Route::name('tes')->get('tes', function () {
    return view('tes');
});
Route::group(['namespace' => 'Blog'], function() {
    Route::name('home')->get('/', 'HomeController@index');

    Route::name('artikel.list')->get('/artikel', 'NewsController@index');
    Route::name('artikel.detail')->get('/artikel/{slug}', 'NewsController@show');

    // Route::name('tentang_kami')->get('tentang-kami', function () {
    //     return view('front.about_us');
    // });
    Route::name('kontak_kami')->get('kontak-kami', 'ContactController@index');
    Route::name('kategori.list')->get('/kategori/{slug}', 'HomeController@category_detail');
    Route::name('agenda.index')->get('/agenda', 'ScheduleController@index');
    Route::name('agenda.list')->get('/agenda/{detail}', 'ScheduleController@detail');

    Route::name('pages.detail')->get('/pages/{slug}', 'HomeController@pages');
    Route::name('tag.list')->get('/tag/{slug}', 'HomeController@tag');
    Route::name('comment.post')->post('/comment', 'HomeController@comment');
    Route::name('searchajax')->get('/searchajax', 'HomeController@autoComplete');
    Route::name('portfolio')->get('/portfolio', 'HomeController@gallery');
    // Route::name('search')->post('/search', 'SearchController');
    Route::name('home.contact')->post('/home/contact', 'ContactController@sendMail');
});

Route::group(['prefix' => 'adm'], function () {
  Auth::routes();

  Route::group(['namespace' => 'Admin'], function() {

    Route::name('adm')->get('/', 'HomeController@index');

    Route::resource('/agenda', 'AgendaController');
    Route::get('/agenda/edit/{id}', 'AgendaController@edit');
    Route::put('/agenda/update/{id}', 'AgendaController@update');
    Route::get('/agenda/show/{id}', 'AgendaController@show');

    Route::resource('/album', 'AlbumController', ['names' => 'adm.album']);
    Route::resource('/banner', 'BannerController', ['names' => 'adm.banner']);
    Route::resource('/category', 'CategoryController', ['names' => 'adm.category']);
    Route::resource('/client', 'ClientController', ['names' => 'adm.client']);
    Route::resource('/comment', 'CommentController', ['names' => 'adm.comment']);
    // Route::name('adm.comment.index')->get('/comment', 'CommentController@index');
    // Route::name('adm.comment.show')->get('/comment/show/{comment}', 'CommentController@show');
    Route::name('comment.destroy')->delete('/comment/destroy/{comment}', 'CommentController@destroy');

    Route::name('contact.count')->get('/contact/count-message', 'ContactController@countMessage');
    Route::resource('/contact', 'ContactController', ['names' => 'adm.contact']);

    Route::resource('/galery', 'GaleryController', ['names' => 'adm.galery']);
    Route::resource('/identity', 'IdentityController', ['names' => 'adm.identity']);
    Route::resource('/identity_social', 'IdentitySocialController', ['names' => 'adm.identity_social']);
    Route::resource('/menu', 'MenuController', ['names' => 'adm.menu']);
    Route::resource('/news', 'NewsController', ['names' => 'adm.news']);
    Route::resource('/staticpages', 'StaticpagesController', ['names' => 'adm.staticpages']);
    Route::resource('/tag', 'TagController', ['names' => 'adm.tag']);
    Route::resource('/user', 'UserController', ['names' => 'adm.user']);

    Route::name('profil.change_password')->get('/profil/change-password/{id}', 'UserPasswordController@changePassword');
    Route::name('profil.change_password.update')->put('/profil/change-password/{id}', 'UserPasswordController@update');
    Route::name('profil.store')->post('/profil/store', 'UserProfilController@store');
    Route::name('profil.update')->put('/profil/update/{id}', 'UserProfilController@update');

    Route::get('/user/getposts', ['as'=>'adm.user.getposts','uses'=>'UserController@getPosts']);
    Route::name('adm.profil')->get('/profil', 'UserController@profil');
    Route::name('adm.profil.edit')->get('/edit_profil/{id}', 'UserController@edit_profil');

  });

});

app/Http/Controllers/Admin/TagController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\TagRequest;
use Illuminate\Support\Str;

use App\TagModel;
use Ramsey\Uuid\Uuid;
use Session;
use Alert;

class TagController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
      $tag = TagModel::orderBy('created_at', 'desc')->get();
      return view('admin.tag.index', compact('tag'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tag.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TagRequest $request)
    {
      $data['id'] = Uuid::uuid4()->toString();
      $data['tag_name'] = $request->tag_name;
      $data['tag_slug'] = Str::slug($request->tag_name);
      $data['created_at'] = date('Y-m-d H:i:s');

      if (TagModel::insert($data)) {
          Alert::success('Data berhasil ditambah !', 'Sukses');
          return redirect('adm/tag');
       }else{
          Alert::error('Silahkan di coba lagi !', 'Error');
          return redirect('adm/tag');
       }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if ($id!='') {
            $data['tags'] = TagModel::where(array('id' => $id))->get()->first();
            return view('admin.tag.edit', $data);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if ($id != '') {
            if (TagModel::where('id', $id)->delete()){
                Alert::success('Data berhasil dihapus', 'Sukses');
                return redirect('adm/tag');
            }else{
                Alert::error('Data tidak berhasil dihapus', 'Error');
                return redirect('adm/tag');
            }
        }
    }
}

resources/views/admin/tag/create.blade.php
@extends('layouts.admin.template')
@section('title', 'Add Tags')

@section('breadcrumb')
<div id="breadcrumb">
	<ul class="breadcrumb">
		 <li><i class="fa fa-home"></i><a onclick="location.href='{{ route('adm') }}'"> Home</a></li>
		 <li></i><a onclick="location.href='{{ url('staticpages') }}'"> Static Pages</a></li>
		 <li class="active">Add</li>
	</ul>
</div>
@endsection

@section('content')
<div class="panel panel-primary">
	<div class="panel-heading">Add Tags</div>
	<div class="panel-body">
		{!! Form::open(array('route' => 'tag.store', 'methode' => 'POST', 'class' => 'form-horizontal', 'enctype' => 'multipart/form-data')) !!}
		<div class="form-group">
			<label for="tag_name" class="col-sm-2 control-label">Tag Name</label>
			<div class="col-sm-10">
				<input type="text" name="tag_name" class="form-control" id="tag_name" placeholder="Tag Name" autocomplete="off">
			</div>
		</div>

		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Simpan</button>
				<a onclick="location.href='{{ route('staticpages.index') }}'" class="btn btn-danger"><i class="fa fa-arrow-left"></i> Kembali</a>
			</div>
		</div>
		{!! Form::close() !!}
	</div>
</div>
@endsection

@section('style')
<link href="{{ asset('admin/js/ckeditor/content.css') }}" rel="stylesheet"/>
<link href="{{ asset('admin/css/gritter/jquery.gritter.css') }}" rel="stylesheet">
@endsection

@section('js')
<script src="{{ asset('admin/js/ckeditor/ckeditor.js') }}"></script>
<script src="{{ asset('admin/js/ckeditor/script/sample.js') }}"></script>
<script src="{{ asset('admin/js/jquery.gritter.min.js') }}"></script>
<script>
	initSample();
	$('.picture').change(function()	{
		var filename = $(this).val().split('\\').pop();
		$(this).parent().find('span').attr('data-title',filename);
		$(this).parent().find('label').attr('data-title','Change file');
		$(this).parent().find('label').addClass('selected');
	});
</script>

@if(count($errors) > 0)
    @foreach($errors->all() as $error)
        <script>
			$.gritter.add({
				title: '<i class="fa fa-warning"></i> Error',
				text: '{{ $error }}',
				sticky: false,
				time: '5000',
				class_name: 'gritter-danger'
			});
        </script>
    @endforeach
@endif

@endsection

resources/views/admin/tag/index.blade.php
@extends('layouts.admin.template')
@section('title', 'Tag')
@section('breadcrumb')
<div id="breadcrumb">
	<ul class="breadcrumb">
		 <li><i class="fa fa-home"></i><a onclick="location.href='{{ route('adm') }}'"> Home</a></li>
		 <li class="active">Tag</li>
	</ul>
</div>
@endsection
@section('content')
<div class="panel panel-primary table-responsive">
	<div class="panel-heading">&nbsp;</div>
	<div class="padding-md clearfix">
		@section('button')
		<a onclick="location.href='{{route('adm.tag.create')}}'" class="btn btn-primary btn-small"><i class="fa fa-plus"></i> Add @yield('title') </a>
		@endsection
		<table class="table table-condensed table-bordered" id="dataTable">
			<thead>
				<tr>
					<th width="20px">No</th>
					<th>Tag Name</th>
					<th>Tag Slug</th>
					<th>Count</th>
					<th width="100px">Action</th>
				</tr>
			</thead>
			<tbody>
				@if(!$tag->isEmpty())
				@php $no=0; @endphp
				@foreach($tag as $r)
				@php $no++; @endphp
				<tr>
					<td>{{ $no }}</td>
					<td>{{ $r->tag_name }}</td>
					<td>{{ $r->tag_slug }}</td>
					<td>{{ $r->count }}</td>
					<td>
						<a href="{{ route('adm.tag.edit', $r->id)  }}" class="btn btn-xs btn-primary"><i class="fa fa-pencil"></i></a>
						{!! Form::open(['route' => ['adm.tag.destroy', $r->id], 'method' => 'DELETE', 'class' => 'delete_form', 'style' => 'display:inline']) !!}
            {{ csrf_field() }}
						<button class="btn btn-danger btn-xs delete_button"><i class="fa fa-trash"></i></button>
						{!! Form::close() !!}
					</td>
				</tr>
				@endforeach
				@endif
			</tbody>
		</table>
	</div>
</div>
@endsection

@section('style')
<link href="{{ asset('admin/css/jquery.dataTables_themeroller.css') }}" rel="stylesheet">
<link href="{{ asset('admin/css/sweetalert.css') }}" rel="stylesheet">
@endsection

@section('js')
<script src="{{ asset('admin/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin/js/sweetalert.min.js') }}"></script>
<script>
    $('button.delete_button').on('click', function(e){
    	e.preventDefault();
    	var self = $(this);
    	swal({
        title: "Alert",
        text: "Apakah anda yakin ingin menghapus data ini ?",
        type: "warning",
        showCancelButton: true,
        confirmButtonColor: "#cc3f44",
        confirmButtonText: "Hapus",
        cancelButtonText : "Batal",
        closeOnConfirm: false,
        closeOnCancel: false
    	},
    	function(isConfirm) {
	        if(isConfirm){
	        	self.parents(".delete_form").submit();
	        }else{
	        	swal('Cancelled', 'Data anda gagal dihapus !', 'error');
	        }
	    });
    });
</script>
<script>
	$(function	()	{
		$('#dataTable').dataTable( {
			"bJQueryUI": true,
			"sPaginationType": "full_numbers"
		});
	});
</script>
@endsection