routes/web.php
<?php

Route::name('tes')->get('tes', function () {
    return view('tes');
});
Route::group(['namespace' => 'Blog'], function() {
    Route::name('home')->get('/', 'HomeController@index');

    Route::name('artikel.list')->get('/artikel', 'NewsController@index');
    Route::name('artikel.detail')->get('/artikel/{slug}', 'NewsController@show');

    // Route::name('tentang_kami')->get('tentang-kami', function () {
    //     return view('front.about_us');
    // });
    Route::name('kontak_kami')->get('kontak-kami', 'ContactController@index');
    Route::name('kategori.list')->get('/kategori/{slug}', 'HomeController@category_detail');
    Route::name('agenda.index')->get('/agenda', 'ScheduleController@index');
    Route::name('agenda.list')->get('/agenda/{detail}', 'ScheduleController@detail');

    Route::name('pages.detail')->get('/pages/{slug}', 'HomeController@pages');
    Route::name('tag.list')->get('/tag/{slug}', 'HomeController@tag');
    Route::name('comment.post')->post('/comment', 'HomeController@comment');
    Route::name('searchajax')->get('/searchajax', 'HomeController@autoComplete');
    Route::name('portfolio')->get('/portfolio', 'HomeController@gallery');
    // Route::name('search')->post('/search', 'SearchController');
    Route::name('home.contact')->post('/home/contact', 'ContactController@sendMail');
});

Route::group(['prefix' => 'adm'], function () {
  Auth::routes();

  Route::group(['namespace' => 'Admin'], function() {

    Route::name('adm')->get('/', 'HomeController@index');

    Route::resource('/agenda', 'AgendaController');
    Route::get('/agenda/edit/{id}', 'AgendaController@edit');
    Route::put('/agenda/update/{id}', 'AgendaController@update');
    Route::get('/agenda/show/{id}', 'AgendaController@show');

    Route::resource('/album', 'AlbumController', ['names' => 'adm.album']);
    Route::resource('/banner', 'BannerController', ['names' => 'adm.banner']);
    Route::resource('/category', 'CategoryController', ['names' => 'adm.category']);
    Route::resource('/client', 'ClientController', ['names' => 'adm.client']);
    Route::resource('/comment', 'CommentController', ['names' => 'adm.comment']);
    // Route::name('adm.comment.index')->get('/comment', 'CommentController@index');
    // Route::name('adm.comment.show')->get('/comment/show/{comment}', 'CommentController@show');
    Route::name('comment.destroy')->delete('/comment/destroy/{comment}', 'CommentController@destroy');

    Route::name('contact.count')->get('/contact/count-message', 'ContactController@countMessage');
    Route::resource('/contact', 'ContactController', ['names' => 'adm.contact']);

    Route::resource('/galery', 'GaleryController', ['names' => 'adm.galery']);
    Route::resource('/identity', 'IdentityController', ['names' => 'adm.identity']);
    Route::resource('/identity_social', 'IdentitySocialController', ['names' => 'adm.identity_social']);
    Route::resource('/menu', 'MenuController', ['names' => 'adm.menu']);
    Route::resource('/news', 'NewsController', ['names' => 'adm.news']);
    Route::resource('/staticpages', 'StaticpagesController', ['names' => 'adm.staticpages']);
    Route::resource('/tag', 'TagController', ['names' => 'adm.tag']);
    Route::resource('/user', 'UserController', ['names' => 'adm.user']);

    Route::name('profil.change_password')->get('/profil/change-password/{id}', 'UserPasswordController@changePassword');
    Route::name('profil.change_password.update')->put('/profil/change-password/{id}', 'UserPasswordController@update');
    Route::name('profil.store')->post('/profil/store', 'UserProfilController@store');
    Route::name('profil.update')->put('/profil/update/{id}', 'UserProfilController@update');

    Route::get('/user/getposts', ['as'=>'adm.user.getposts','uses'=>'UserController@getPosts']);
    Route::name('adm.profil')->get('/profil', 'UserController@profil');
    Route::name('adm.profil.edit')->get('/edit_profil/{id}', 'UserController@edit_profil');

  });

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    public $incrementing = false;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id', 'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function profile()
    {
      return $this->hasOne(UserProfilModel::class, 'user_id');
    }

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\UserRequest;
use Illuminate\Support\Facades\Auth;

use DataTables;

use App\{ UserModel, UserProfilModel };
use Ramsey\Uuid\Uuid;
use Session;
use Alert;
use LogActivity;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        DB::statement(DB::raw('set @nomor=0 '));
        $users = UserModel::select(DB::raw('@nomor := @nomor + 1 as no'), 'id','name', 'email', 'created_at')
            ->orderBy('users.created_at', 'desc')->get();
        return view('admin.user.index', compact('users'));
    }

    public function create()
    {
        return view('admin.user.create');
    }

    public function show($id)
    {

    }

    public function store(UserRequest $request)
    {
        $data['id'] = Uuid::uuid4()->toString();
        $data['name'] = $request->name;
        $data['password'] = bcrypt($request->password);
        $data['email'] = $request->email;
        $data['created_at'] = date('Y-m-d H:i:s');

        if (UserModel::insert($data)) {
            Alert::success('Data berhasil disimpan', 'Sukses');
            return redirect('adm/user');
         }else{
            Alert::error('Silahkan coba lagi !', 'Error');
            return redirect('adm/user');
         }
    }

    public function edit($id)
    {
        if ($id!='')
        {
            $data['users'] = UserModel::where('id',$id)->get()->first();
            return view('admin.user.edit', $data);
        }
    }

    public function update(UserRequest $request, $id)
    {
        if ($request->password == '') {
            $data['name'] = $request->name;
            $data['email'] = $request->email;
            $data['updated_at'] = date('Y-m-d H:i:s');
        }else {
            $data['name'] = $request->name;
            $data['email'] = $request->email;
            $data['password'] = bcrypt($request->password);
            $data['updated_at'] = date('Y-m-d H:i:s');
        }

        if (UserModel::where('id', $id)->update($data)) {
            Alert::success('Data berhasil disimpan', 'Sukses');
            return redirect('adm/user');
         }else{
            Alert::error('Silahkan di coba lagi !', 'Error');
            return redirect('adm/user/edit/'.$id);
         }
    }

    public function destroy($id)
    {
        if ($id != '') {
            if (UserModel::where('id', $id)->delete()){
                Alert::success('Data berhasil dihapus', 'Sukses');
                return redirect('adm/user');
            }else{
                Alert::error('Silahkan di coba lagi !', 'Error');
                return redirect('adm/user');
            }
        }
    }

    public function profil(Request $request)
    {
        $usr = UserModel::find(Auth::user()->id);
        $data['id'] = $usr->id;

        $data['users'] = UserModel::where('id', $usr->id)->first();
        $data['profil'] = UserProfilModel::where('user_id', $usr->id)->first();
        $data['cek'] = UserProfilModel::where('user_id', $usr->id)->get();

        return view('admin.user.profil', $data);
    }

    public function edit_profil($id)
    {
        $users = UserModel::where('id', $id)->first();
        $profil = UserProfilModel::where('user_id', $id)->first();
        $cek = UserProfilModel::where('user_id', $id)->first();

        if ($cek->count() < 1) {
            return view('admin.user_profil.create', compact('users', 'profil', 'cek'));
        }else{
            return view('admin.user_profil.edit', compact('users', 'profil', 'cek'));
        }
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.admin.template')
@section('title', 'Add Users')
@section('breadcrumb')
<div id="breadcrumb">
	<ul class="breadcrumb">
		 <li><i class="fa fa-home"></i><a onclick="location.href='{{ route('adm') }}'"> Home</a></li>
		 <li></i><a onclick="location.href='{{ route('adm.user.index') }}'"> User</a></li>
		 <li class="active">Add</li>
	</ul>
</div>
@endsection
@section('content')
<div class="panel panel-primary">
	<div class="panel-heading">Add User</div>
	<div class="panel-body">
		{!! Form::open(['route' => 'adm.user.store', 'methode' => 'POST', 'class' => 'form-horizontal']) !!}

		<div class="form-group">
			<label for="name" class="col-sm-2 control-label">Username</label>
			<div class="col-sm-10">
				<input type="text" name="name" class="form-control" id="name" placeholder="Username" autocomplete="off">
			</div>
		</div>
		<div class="form-group">
			<label for="email" class="col-sm-2 control-label">Email</label>
			<div class="col-sm-10">
				<input type="text" name="email" class="form-control" id="email" placeholder="Email" autocomplete="off">
			</div>
		</div>
		<div class="form-group">
			<label for="passsword" class="col-sm-2 control-label">Password</label>
			<div class="col-sm-10">
				<input type="password" name="password" class="form-control" id="passsword" placeholder="Password" autocomplete="off">
			</div>
		</div>

		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Simpan</button>
				<a href="{{ route('adm.user.index') }}" class="btn btn-danger"><i class="fa fa-arrow-left"></i> Kembali</a>
			</div>
		</div>
		{!! Form::close() !!}
	</div>
</div>
@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.admin.template')
@section('title', 'Edit Users')
@section('breadcrumb')
<div id="breadcrumb">
	<ul class="breadcrumb">
		 <li><i class="fa fa-home"></i><a href="" onclick="location.href='{{ route('adm') }}'"> Home</a></li>
		 <li><a href="" onclick="location.href='{{ route('adm.user.index') }}'">User</a></li>
		 <li class="active">Edit</li>
	</ul>
</div>
@endsection

@section('content')

<section class="panel panel-primary">
	<header class="panel-heading">Edit Data User</header>
	<div class="panel-body">

	{!! Form::open(['route' => ['adm.user.update', $users->id], 'method' => 'put', 'class' => 'form-horizontal']) !!}

		<div class="form-group">
			<label for="username" class="col-sm-2 control-label">Username</label>
			<div class="col-sm-10">
				<input type="text" name="name" class="form-control" id="name" placeholder="Username" value="{{ $users->name }}" autocomplete="off">
			</div>
		</div>
		<div class="form-group">
			<label for="email" class="col-sm-2 control-label">Email</label>
			<div class="col-sm-10">
				<input type="text" name="email" class="form-control" id="email" placeholder="Username" value="{{ $users->email }}" autocomplete="off">
			</div>
		</div>
		<div class="form-group">
			<label for="password" class="col-sm-2 control-label">Password</label>
			<div class="col-sm-10">
				<input type="password" name="password" class="form-control" id="password" placeholder="Password" autocomplete="off">
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Simpan</button>
				<a href="{{ route('adm.user.index') }}" class="btn btn-danger"><i class="fa fa-arrow-left"></i> Kembali</a>
			</div>
		</div>
	{!! Form::close() !!}

	</div>
</section>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.admin.template')
@section('title', 'Users')

@section('breadcrumb')
<div id="breadcrumb">
	<ul class="breadcrumb">
		 <li><i class="fa fa-home"></i><a onclick="location.href='{{ route('adm') }}'"> Home</a></li>
		 <li class="active">User</li>
	</ul>
</div>
@endsection

@section('content')
<div class="panel panel-primary table-responsive">
	<div class="panel-heading">
		Data User
	</div>
	<div class="padding-md clearfix">
		@section('button')
		<a href="{{ route('adm.user.create') }}" class="btn btn-primary btn-small"><i class="fa fa-plus"></i> Add User </a>
		@endsection
		<table class="table table-condensed table-bordered" id="dataTable">
			<thead>
				<tr>
					<th width="20px">No</th>
					<th>Name</th>
					<th>Email</th>
					<th>Created At</th>
					<th width="80px">Action</th>
				</tr>
			</thead>
			<tbody>
				@if(!$users->isEmpty())
				@foreach($users as $r)
				<tr>
					<td>{{ $r->no }}</td>
					<td>{{ $r->name }}</td>
					<td>{{ $r->email }}</td>
					<td>{{ $r->created_at }}</td>
					<td>
						@if(Auth::user()->id != $r->id)
						<a href="{{ route('adm.user.edit', $r->id) }}" class="btn btn-xs btn-primary"><i class="fa fa-pencil"></i></a>
						{!! Form::open(['route' => ['adm.user.destroy', $r->id], 'method' => 'DELETE', 'class' => 'delete_form', 'style' => 'display:inline']) !!}
						<button class="btn btn-danger btn-xs delete_button"><i class="fa fa-trash"></i></button>
						{!! Form::close() !!}
						@endif
					</td>
				</tr>
				@endforeach
				@endif
			</tbody>
		</table>
	</div>
</div>
@endsection

@section('style')
<link href="{{ asset('admin/css/jquery.dataTables_themeroller.css') }}" rel="stylesheet">
<link href="{{ asset('admin/css/sweetalert.css') }}" rel="stylesheet">
@endsection

@section('js')
<script src="{{ asset('admin/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin/js/sweetalert.min.js') }}"></script>
<script>
	$(function	()	{
			$('#dataTable').dataTable( {
				"bJQueryUI": true,
				"bLengthChange": false,
				"sPaginationType": "full_numbers"
			});
	    $('button.delete_button').on('click', function(e){
	    	e.preventDefault();
	    	var self = $(this);
	    	swal({
	        title: "Alert",
	        text: "Apakah anda yakin ingin menghapus data ini ?",
	        type: "warning",
	        showCancelButton: true,
	        confirmButtonColor: "#cc3f44",
	        confirmButtonText: "Hapus",
	        cancelButtonText : "Batal",
	        closeOnConfirm: false,
	        closeOnCancel: false
	    	},
	    	function(isConfirm) {
		        if(isConfirm){
		        	self.parents(".delete_form").submit();
		        }else{
		        	swal('Cancelled', 'Data anda gagal dihapus !', 'error');
		        }
		    });
	    });
		});
</script>
@endsection

resources/views/admin/user/profil.blade.php
@extends('layouts.admin.template')
@section('title', 'Profil Users')

@section('breadcrumb')
<div id="breadcrumb">
	<ul class="breadcrumb">
		 <li><i class="fa fa-home"></i><a onclick="location.href='{{ route('adm') }}'"> Home</a></li>
		 <li class="active">User</li>
	</ul>
</div>
@endsection

@section('content')
<ul class="tab-bar grey-tab">
	<li class="active">
		<a href="#overview">
			<span class="block text-center"><i class="fa fa-home fa-2x"></i></span>
			Overview
		</a>
	</li>
	<li>
		<a href="{{ route('adm.profil.edit', $id) }}">
			<span class="block text-center"><i class="fa fa-edit fa-2x"></i></span>
			Edit Profile
		</a>
	</li>
</ul>

<div class="padding-md">
	<div class="row">
		<div class="col-md-3 col-sm-3">
			<div class="row">
				<div class="col-xs-6 col-sm-12 col-md-6 text-center">
					<a href="#">
						@if(empty($cek->picture))
						<img src="{{ asset('admin/img/unknown.png') }}" alt="User Avatar" class="img-thumbnail">
						@else
						<img src="{{ asset('admin/img/'.$cek->picture) }}" alt="User Avatar" class="img-thumbnail">
						@endif
					</a>
					<div class="seperator"></div>
					<div class="seperator"></div>

				</div><!-- /.col -->
				<div class="col-xs-6 col-sm-12 col-md-6">
					<strong class="font-14">{{ $users->name }}</strong>
					<small class="block text-muted">{{ $users->email }}</small>
					<div class="seperator"></div>
					<a href="#" class="social-connect tooltip-test facebook-hover pull-left m-right-xs" data-toggle="tooltip" data-original-title="Facebook"><i class="fa fa-facebook"></i></a>
					<a href="#" class="social-connect tooltip-test twitter-hover pull-left m-right-xs" data-toggle="tooltip" data-original-title="Twitter"><i class="fa fa-twitter"></i></a>
					<a href="#" class="social-connect tooltip-test google-plus-hover pull-left" data-toggle="tooltip" data-original-title="Google Plus"><i class="fa fa-google-plus"></i></a>
					<div class="seperator"></div>
					<div class="seperator"></div>
					<br>
					<button type="button" class="btn btn-info btn-xs btn-detail"  onclick="location.href='{{ route('profil.change_password', $users->id) }}'">Ubah Password</button>
				</div><!-- /.col -->
			</div><!-- /.row -->
			@if(count($cek) < 1)
			<div class="alert alert-danger">Anda belum melengkapi profil anda ! Klik <a href="{{ route('adm.profil.edit', $users->id) }}">disini</a> untuk melengkapi profil anda.</div>
			@endif
		</div><!-- /.col -->
		<div class="col-md-9 col-sm-9">
			<div class="tab-content">
				<div class="tab-pane fade in active" id="overview">
					<div class="row">
						<div class="col-md-12">
							<div class="panel panel-default fadeInDown animation-delay2">
								<div class="panel-heading">
									<h4><b>My Profile</b></h4>
								</div>
								<div class="panel-body">
									<p>
										<table class="table table-striped">
											<tr><td width="175px">Full Name</td> <td>{{ empty($profil->full_name) ? '' : $profil->full_name }}</td></tr>
											<tr><td>Gender</td>            <td>{{ empty($profil->sex) ? '' : $profil->sex }}</td></tr>
											<tr><td>Phone Number</td>      <td>{{ empty($profil->phone_number) ? '' : $profil->phone_number }}</td></tr>
											<tr><td>Address</td>           <td>{{ empty($profil->address) ? '' : $profil->address }}</td></tr>
											<tr><td>Google</td>            <td>{{ empty($profil->google) ? '' : $profil->google }}</td></tr>
											<tr><td>Facebook</td>          <td>{{ empty($profil->facebook) ? '' : $profil->facebook}}</td></tr>
											<tr><td>Twitter</td>           <td>{{ empty($profil->twitter) ? '' : $profil->twitter }}</td></tr>
											<tr><td>Youtube</td>           <td>{{ empty($profil->youtube) ? '' : $profil->youtube  }}</td></tr>
											<tr><td>Path</td>              <td>{{ empty($profil->path) ? '' : $profil->path }}</td></tr>
											<tr><td>Description</td>       <td>{{ empty($profil->description) ? '' : $profil->description }}</td></tr>
										</table>
									</p>
								</div>
							</div><!-- /panel -->
						</div><!-- /.col -->
					</div><!-- /.row -->
				</div><!-- /tab1 -->
			</div><!-- /tab-content -->
		</div><!-- /.col -->
	</div><!-- /.row -->
</div><!-- /.padding-md -->
<div class="modal fade bs-example-modal-md" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-body" style="max-height: calc(100vh - 100px); overflow-y: auto;">
        <div id="modalcontent"></div>
      </div>
    </div>
  </div>
</div>
@endsection

@section('style')
<link href="{{ asset('admin/css/sweetalert.css') }}" rel="stylesheet">
@endsection

@section('js')
<script src="{{ asset('admin/js/sweetalert.min.js') }}"></script>
@endsection